version: "3.9"

services:
  backend:
    build: ./server
    container_name: ecommerce-backend
    image: backend
    ports:
      - "5500:5500"
    env_file:
      - ./server/.env
    networks:
      - ecommerce-network
    restart: always

  frontend:
    build: ./client
    container_name: ecommerce-frontend
    image: frontend
    expose:
      - "80"     
    env_file:
      - ./client/.env
    depends_on:
      - backend
    networks:
      - ecommerce-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
